---
- name: Apt update
  become: yes
  apt:
    update_cache: yes

- name: Install docker dependencies
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Add an Apt signing key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Apt update
  become: yes
  apt:
    update_cache: yes

- name: Install docker
  become: yes
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Start service docker
  become: yes
  service:
    name: docker
    state: restarted

- name: Add user to the group of 'docker'
  become: yes
  user:
    name: "{{ansible_user}}"
    groups: docker
    append: yes
